version: '3.1'

services:
  db:
    image: aornatovskyy/ai-db
    container_name: postgres-db
    restart: always
    networks:
      - mynetwork
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres

  zone-app:
    image: aornatovskyy/ai:latest
    restart: always
    networks:
      - mynetwork
    ports:
      - 7070:8080
networks:
  mynetwork:
