spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/test_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml
optaplanner:
  solver:
    termination:
      unimproved-spent-limit: 2s
